label: acapy-plugin-rd

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: false
admin-api-key: change-me
jwt-secret: change-me


# Transport
inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

webhook: http://host.docker.internal:3000

enable-undelivered-queue: true

# plugins
plugin:
  - aries_cloudagent.messaging.jsonld
  #- plugins.add_endpoint
  #- plugins.override_protocol
  - plugins.multitenant_multitoken

#block-plugin:
# - aries_cloudagent.protocols.connections

#invite: true
#invite-label: ACA-Py (R&D)

#config 
genesis-url: http://test.bcovrin.vonx.io/genesis

wallet-type: 'indy'
wallet-name: traction-wallet
wallet-key: 'insecure-change-me'
wallet-storage-type: postgres_storage
wallet-storage-config: '{"url":"host.docker.internal:5432","max_connections":5,"wallet_scheme":"MultiWalletSingleTableSharedPool"}'
wallet-storage-creds: '{"account":"postgres","password":"postgresPass","admin_account":"postgres","admin_password":"postgresPass"}'

log-level: info
multitenant: true
multitenant-admin: true

emit-new-didcomm-prefix: true

auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-store-credential: true
auto-verify-presentation: true
auto-ping-connection: true
auto-provision: true
monitor-ping: true
public-invites: true
