version: "3.9"
services:
  traction-agent:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      traction-db:
        condition: service_healthy
    ports:
      - 3001:3001
      - 3000:3000
      - 3002:3002
    extra_hosts:
      - host.docker.internal:host-gateway

  traction-db:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=postgresPass
    ports:
      - 5432:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  traction-wallet: